### PR TITLE
User as object

### PR DESCRIPTION
**Pull request by SysPete**
@abeverley @racke please review.

This requires the latest master branch of D2PAE which adds support for logged_in_user being an object to the tests.

### CODE REVIEW

**Comment by abeverley** [comment]
Brilliant, thanks @SysPete 

Just one comment. Did you mean to remove [this](https://github.com/ctrlo/Dancer2-Plugin-Auth-Extensible-Provider-DBIC/pull/14/files#diff-78cae4833fdc32ec16da934373a572ddL624)? It breaks [the roles_key functionality](https://metacpan.org/pod/Dancer2::Plugin::Auth::Extensible::Provider::DBIC#roles_key). Whilst I will move to objects for logged_in_user soon, it means I can't use the upgraded version for existing apps for the time being.

**Comment by SysPete** [comment]
@abeverley I didn't spot roles_key - will get this sorted ASAP.

**Comment by SysPete** [comment]
@abeverley how about I add this back for the hash-based user but mark it as deprecated in POD? You can get the same anyway via `user_has_role($user,$role)`.

**Comment by SysPete** [comment]
Time to expand my thinking a little...

DPAE providers should really only provide methods as required by the main plugin and should not add extra local functionality since this makes migrating between providers more difficult. The `roles_key` functionality could be added via the `after_login_success` hook at which point a user can do whatever they like with the cached user hash/object. Perhaps we could even move `roles_key` this into the main plugin?

@racke any thoughts?

**Comment by abeverley** [comment]
@SysPete - thanks for the thoughts. I agree in principle with all the above, but obviously any removal needs to be managed carefully as it might not be just me using it. I'll just switch to the object, but for completeness I would say that:
- `user_has_role` can only be used from somewhere where the plugin has been loaded. I've been doing (for example) `user.permission.admin` in a template
- adding something in `after_login_success` works, but would mean a second hit to the database when it could have all been prefetched

Like I say though, I have no formal objection to its removal as I'll move to the user object, but I just wanted to highlight the above. Thanks!

**Comment by SysPete** [comment]
Commit daff928436e9fbe216060862efea2dcc9baa3d20 reinstates `roles_key` for hash-based user. It also updates `set_user_details` to avoid the roles_key-dependent code in there for obj-based user.

For avoiding database hits I'm planning on making changes to ensure that logged_in_user get cached in a var along with roles data. For DBIC `user_as_object` this just means that the query used to find the user will prefetch the related roles table entries. Some changes to D2PAE are needed to make this easier - coming soon!

**Pull request closed without merging**
